### ISSUE TITLE
Need to drop events SW1-1 and SW1-2

### ISSUE THREAD

**Issue by limnoliver** [limnoliver/GLRIeof#13]
These events came about prior to the rain gauge being installed - so have no rain metrics associated with this event.

**Comment by rbcarvin** [comment]
It might be worth looking for nearby rain gauges that might have recorded those events. Could compare with the first several events that were recorded at SW1 to see if the nearby rain gauge is a decent surrogate?

**Comment by limnoliver** [comment]
Todd and I chatted about this - he doesn't think there are any nearby rain gauges that were online then. Also, we looked at those two events are they are relatively small, so shouldn't be too much of an issue to drop.

**Comment by rbcarvin** [comment]
Ok, sounds good.
